# Generated by Django 2.1.7 on 2019-02-27 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('manufacturer', models.TextField()),
                ('version', models.TextField()),
                ('part_number', models.TextField(null=True)),
                ('data_sheet', models.URLField(default=None, null=True)),
                ('additional_info', models.TextField(default=None, null=True)),
                ('is_sensor', models.BooleanField()),
                ('parameter', models.TextField(default=None, null=True)),
                ('raw_type_summary', models.TextField(default=None, null=True)),
                ('raw_data_type', models.TextField(default=None, null=True)),
                ('vsr_data_type', models.TextField(default=None, null=True)),
                ('vsr_unit', models.TextField(default=None, null=True)),
                ('vsr_min_value', models.FloatField(default=None, null=True)),
                ('vsr_max_value', models.FloatField(default=None, null=True)),
                ('vsr_accuracy', models.FloatField(default=None, null=True)),
                ('vsr_context', models.TextField(default=None, null=True)),
            ],
            options={
                'db_table': 'hardware_components',
                'ordering': ('name', '-version'),
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('uid', models.TextField()),
                ('calibration', models.TextField(default=None, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hardware.Component')),
            ],
            options={
                'db_table': 'hardware_instances',
                'ordering': ('component', 'uid'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='component',
            unique_together={('name', 'manufacturer', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='instance',
            unique_together={('component', 'uid')},
        ),
    ]
