# Generated by Django 2.1.7 on 2019-02-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeset',
            name='object_id',
            field=models.TextField(),
        ),
    ]
