# Generated by Django 2.1.7 on 2019-02-28 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('software', '0001_initial'),
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default=None, null=True, unique=True)),
                ('state', models.TextField(choices=[('build out', 'build out'), ('burn in', 'burn in'), ('testing', 'testing'), ('storage', 'storage'), ('deployed', 'deployed'), ('decommissioned', 'decommissioned')])),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('altitude', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True)),
                ('elevation', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True)),
                ('orientation_x', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True)),
                ('orientation_y', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True)),
                ('orientation_z', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True)),
                ('modem_imei', models.TextField(blank=True, default=None, null=True)),
                ('sim_iccid', models.TextField(blank=True, default=None, null=True)),
                ('ssh_port', models.TextField(blank=True, default=None, null=True)),
                ('ssh_key', models.TextField(blank=True, default=None, null=True)),
                ('ssl_cert', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'nodes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='NodeHardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('expected_state', models.TextField(choices=[('on', 'on'), ('off', 'off')])),
                ('actual_state', models.TextField(choices=[('on', 'on'), ('off', 'off')])),
                ('expected_mode', models.TextField(choices=[('sd', 'sd'), ('emmc', 'emmc')])),
                ('actual_mode', models.TextField(choices=[('sd', 'sd'), ('emmc', 'emmc')])),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='hardware.Instance')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.Node')),
            ],
            options={
                'verbose_name': 'Node Hardware',
                'verbose_name_plural': 'Node Hardware',
                'db_table': 'node_hardware',
                'ordering': ('node', 'name'),
            },
        ),
        migrations.CreateModel(
            name='NodeSoftware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('expected_state', models.TextField(choices=[('running', 'running'), ('stopped', 'stopped')])),
                ('actual_state', models.TextField(choices=[('running', 'running'), ('stopped', 'stopped')])),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.Node')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='software.Software')),
            ],
            options={
                'verbose_name': 'Node Software',
                'verbose_name_plural': 'Node Software',
                'db_table': 'node_software',
                'ordering': ('node',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='tags',
            field=models.ManyToManyField(to='nodes.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='nodesoftware',
            unique_together={('node', 'software')},
        ),
        migrations.AlterUniqueTogether(
            name='nodehardware',
            unique_together={('name', 'node', 'instance')},
        ),
    ]
