# Generated by Django 2.1.7 on 2019-02-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_auto_20190228_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
