# Generated by Django 2.1.7 on 2019-02-27 19:54

from django.db import migrations, models
import software.models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='docs_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='source_tarball',
            field=models.FileField(blank=True, default=None, null=True, upload_to=software.models.software_upload_path),
        ),
        migrations.AlterField(
            model_name='software',
            name='source_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
